### ISSUE TITLE
CHK2 instructions use signed, not unsigned

### ISSUE THREAD

**Issue by jotd666** [kstenerud/Musashi#70]
the code for CHK2 is incorrect. It "works" for bounds like 0 => 10 for instance. But as soon as sign comes into play it fails.

I have an application that performs sanity checks and it fails with the original code. It works perfectly on the real board of course, and also with Basilisk/WinUAE core. Ex: chk2.w where the bounds are -1 => 10 ($FFFF => $A). Of course, treating lower bound as unsigned short fails big time.

Problem in musashi is that lower & upper bound tests should just be read into signed types, and tested as such. It makes the testing code less complicated and compliant to 1) winuae code 2) motorola specs.

**Comment by jotd666** [comment]
here's the fixed version I made. The C flag computation is completely different, and matches Motorola specs. There's also a slight optimization on Z flag computation

[m68k_in.zip](https://github.com/kstenerud/Musashi/files/4301645/m68k_in.zip)

**Comment by tevorbl** [comment]
Hi, I have a similar problem on my project.  Was just about to submit a report of my own, but you've already done one.   

I used your patch and it works for me, so thanks very much.

**Comment by jotd666** [comment]
I'm very glad that it's some use to someone else! I have submitted other fixes through bug reports too for 68040+FPU

**Comment by kstenerud** [comment]
@jotd666 Thanks for looking into this. I've downloaded the zipfile but it's hard to tell what's being done because of the number of changes. Is this a rollup fix of multiple things or just one thing? I saw a change to ANDI so I'm guessing it's multiple things? Could you make a PR for it that describes which issues it's addressing? That way it can clear out the github issues that are solved :)

Github responds to things like `Fixes #9999999` and auto-closes the related issue when a PR containing that text in the description gets merged.

**Comment by jotd666** [comment]
done. I'm not a github expert and did a few things maybe not like you'd prefer

- 1 commit for 2 issues (CPU & FPU)
- one large commit text
- there was an indentation change in one file, resulting in a lot of artificial changes. I think we can disable those diffs but didn't find how.

**Comment by kstenerud** [comment]
Thanks for this :)

Unfortunately, the indenting needs to be restored to what it was before (tab based), because changing tab type really messes up the diffs so that you can't see what changed anymore (you can see what it looks like at the bottom of the [Files Changed tab](https://github.com/kstenerud/Musashi/pull/73/files) (Click on "Load Diff" in `m68kfpu.c`), and also makes things harder in future (for example git bisect and git blame).

There's also a conflict because there have been commits in master since you started working on it, but I think it can be resolved in github if the indentation is resolved.

**Comment by jotd666** [comment]
phew! reported back my changes on m68kfpu.c preserving the original indentation, closed old pull request, and created a new one.

Funny thing, something that I did was already fixed/implemented exactly the same way in the meanwhile (case 0x1e:		// FGETEXP), but in my case I had forgotten a "break;" statement, so this would have introduced a bug. Reviewing the changes while fixing indentation allowed me to spot my error! superb as I can now fix a potential issue in my project! The virtues of contributing to projects instead of changing them for oneself :)
